# Generated by Django 3.2.13 on 2022-05-08 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=150, unique=True, verbose_name='mac address')),
            ],
            options={
                'verbose_name': 'gateway',
                'verbose_name_plural': 'gateways',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='gateway.gateway', verbose_name='gateway')),
            ],
            options={
                'verbose_name': 'sensor',
                'verbose_name_plural': 'sensors',
            },
        ),
    ]
