# Generated by Django 3.2.13 on 2022-05-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_gateway_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='mac',
            field=models.CharField(default=1, max_length=150, unique=True, verbose_name='mac address'),
            preserve_default=False,
        ),
    ]
