# Generated by Django 3.2.13 on 2022-06-16 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0004_auto_20220509_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='gateway',
        ),
        migrations.DeleteModel(
            name='Gateway',
        ),
    ]
