# Generated by Django 3.2.13 on 2022-05-08 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(verbose_name='temperature')),
                ('humidity', models.IntegerField(verbose_name='humidity')),
                ('brightness', models.IntegerField(verbose_name='brightness')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.sensor', verbose_name='sensor')),
            ],
            options={
                'verbose_name': 'sensor data',
                'verbose_name_plural': 'sensor data',
            },
        ),
    ]
