# Generated by Django 3.2.13 on 2022-05-09 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0002_auto_20220509_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='sensor',
        ),
    ]
