# Generated by Django 3.2.13 on 2022-07-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0005_auto_20220616_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='current',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='voltage',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='energy',
            field=models.FloatField(default=1, verbose_name='energy'),
            preserve_default=False,
        ),
    ]
