# Generated by Django 3.2.13 on 2022-07-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0006_auto_20220703_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='time',
            field=models.DateTimeField(verbose_name='time'),
        ),
    ]
