# Generated by Django 3.2.13 on 2022-07-03 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0006_sensor_user'),
        ('data_manager', '0007_alter_sensordata_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sensordata',
            unique_together={('time', 'sensor')},
        ),
    ]
