# Generated by Django 3.2.13 on 2022-05-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_sensor_mac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='id',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='mac',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='mac address'),
        ),
    ]
